apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-test-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
        - image: iesgn/test_web:latest
          name: contenedor-test-web
