apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test-web
  labels:
    app: test-web
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
      - image: iesgn/test_web:version3
        name: contendor-test-web
        ports:
        - name: http
          containerPort: 80

  